apiVersion: v1
kind: Service
metadata:
  name: shell-mf-service
  labels:
    app: shell-mf
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    name: shell-mf-deployment
