import "./globals.scss";
import React from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next (app)",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <header>
        <title>Supplies Module</title>
      </header>
      <body>{children}</body>
    </html>
  );
}
