apiVersion: skaffold/v3
kind: Config
metadata:
  name: hematology-app
requires:
  - configs: ["statistics-mf"]
    path: statistics/statistics-mf/skaffold.yaml
  - configs: ["invoices-mf"]
    path: invoices/invoices-mf/skaffold.yaml
  - configs: ["orders-mf"]
    path: orders/orders-mf/skaffold.yaml
  - configs: ["supplies-mf"]
    path: supplies/supplies-mf/skaffold.yaml
  - configs: ["customers-and-suppliers-mf"]
    path: customers-and-suppliers/customers-and-suppliers-mf/skaffold.yaml
  - configs: ["users-mf"]
    path: users/users-mf/skaffold.yaml
  - configs: ["shell-mf"]
    path: shell/shell-mf/skaffold.yaml
