apiVersion: skaffold/v3
kind: Config
metadata:
  name: hematology-app
requires:
  - configs: ["shell-mf"]
    path: shell/shell-mf/skaffold.yaml
  - configs: ["invoices-mf"]
    path: invoices/invoices-mf/skaffold.yaml
  - configs: ["orders-mf"]
    path: orders/orders-mf/skaffold.yaml
  - configs: ["supplies-mf"]
    path: supplies/supplies-mf/skaffold.yaml
