apiVersion: skaffold/v3
kind: Config
metadata:
  name: supplies-mf
build:
  tagPolicy:
    gitCommit: {}
  local:
    push: false
  artifacts:
    - image: supplies-mf
      context: .
      sync:
        manual:
          - src: "*.d.ts"
            dest: /supplies-mf

          - src: "*.js"
            dest: /supplies-mf

          - src: "*.ts"
            dest: /supplies-mf

          - src: "*.json"
            dest: /supplies-mf

          - src: "src/**/*.scss"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/*.module.scss"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/*.module.css"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/*.module.css.map"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/*.tsx"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/*.scss"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/*.module.scss"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/*.module.css"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/*.module.css.map"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/*.tsx"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/**/*.scss"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/**/*.module.scss"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/**/*.module.css"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/**/*.module.css.map"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/**/*.tsx"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/*.scss"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/*.module.scss"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/*.module.css"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/*.module.css.map"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/*.tsx"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.scss"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.module.scss"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.module.css"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.module.css.map"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.tsx"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.scss"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.module.scss"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.module.css"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.module.css.map"
            dest: /supplies-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.tsx"
            dest: /supplies-mf/src
            strip: "src/"
      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - k8s/cluster-ip-cluster-ip-service.yaml
    - k8s/deployment.yaml

deploy:
  kubectl: {}
