apiVersion: skaffold/v3
kind: Config
metadata:
  name: users-ms
build:
  platforms: ["linux/amd64"]
  tagPolicy:
    gitCommit: {}
  local:
    push: false
  artifacts:
    - image: users-ms
      context: .
      sync:
        manual:
          - src: "src/app.controller.spec.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/app.controller.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/app.module.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/app.service.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/main.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/*.controller.spec.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/*.controller.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/*.entity.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/request.http"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/*.module.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/*.service.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/*.interceptor.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/*.service.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/*.controller.spec.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/*.controller.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/*.dto.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/*.entity.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/*.module.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/*.service.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/*.controller.spec.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/*.controller.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/*.entity.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/*.module.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/*.service.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/*.controller.spec.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/*.controller.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/*.entity.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/*.module.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.service.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.controller.spec.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.controller.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.entity.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.module.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.service.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.controller.spec.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.controller.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.entity.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.module.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/*.service.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/*.controller.spec.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/*.controller.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/*.entity.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/*.module.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/**/*.service.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/**/*.controller.spec.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/**/*.controller.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/**/*.entity.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/**/*.module.ts"
            dest: /users-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/**/*.service.ts"
            dest: /users-ms/src
            strip: "src/"
      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - k8s/ingress.yaml
    - k8s/service.yaml
    - k8s/deployment.yaml

deploy:
  kubectl: {}
