apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-ms-deployment
  labels:
    app: users-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-ms-deployment
  template:
    metadata:
      labels:
        app: users-ms-deployment
    spec:
      containers:
        - image: users-ms
          name: users-ms
          ports:
            - containerPort: 4007
          imagePullPolicy: Never
