apiVersion: v1
kind: ConfigMap
metadata:
  name: users-db-configmap
  labels:
    app: users-db-configmap
data:
  POSTGRES_DB: users-db
  POSTGRES_USER: hematologyapp
  POSTGRES_PASSWORD: hematologyapp
