apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-db-pv
  labels:
    type: localpath
    app: users-db-pv
spec:
  storageClassName: ""
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
