apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-db-pvc
spec:
  #  storageClassName: Will choose the default option automatically
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
