apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-db-pvc
spec:
  storageClassName: ""
  volumeName: users-db-pv
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
