apiVersion: skaffold/v3
kind: Config
metadata:
  name: shell-mf
build:
  platforms: ["linux/amd64"]
  tagPolicy:
    gitCommit: {}
  local:
    push: false
  artifacts:
    - image: shell-mf
      context: .
      sync:
        manual:
<<<<<<< HEAD
          - src: "src/*.module.scss"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/*.module.css"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/*.module.css.map"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/*.js"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/*.module.scss"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/*.jsx"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/*.css"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/*.css.map"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/*.jsx"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/*.scss"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/*.css"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/*.css.map"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/*.jsx"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/*.module.scss"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/*.css"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/*.css.map"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/*.jsx"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/*.module.scss"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/*.css"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/*.css.map"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.jsx"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.module.scss"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.css"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.css.map"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.jsx"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.module.scss"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.css"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.css.map"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/*.jsx"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/*.module.scss"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/*.css"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/*.css.map"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/**/*.jsx"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/**/*.module.scss"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/**/*.css"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/**/*.css.map"
=======
          - src: "src/**"
>>>>>>> b4e4f22 (Sync routes across Micro Frontends)
            dest: /shell-mf/src
            strip: "src/"
      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
<<<<<<< HEAD
    - k8s/ingress.yaml
    - k8s/service.yaml
    - k8s/deployment.yaml
=======
    - k8s/deployment.yaml
    - k8s/cluster-ip-service.yaml
    - k8s/node-port-service.yaml
    - k8s/ingress.yaml
>>>>>>> b4e4f22 (Sync routes across Micro Frontends)

deploy:
  kubectl: {}
