apiVersion: skaffold/v3
kind: Config
metadata:
  name: shell-mf
build:
  tagPolicy:
    gitCommit: {}
  local:
    push: false
  artifacts:
    - image: shell-mf
      context: .
      sync:
        manual:
          - src: "next-env.d.ts"
            dest: /shell-mf

          - src: "next.config.js"
            dest: /shell-mf

          - src: "tsconfig.json"
            dest: /shell-mf

          - src: "src/**/*.scss"
            dest: /shell-mf/src
            strip: "src/"

          - src: "tsconfig.css.map"
            dest: /shell-mf

          - src: "src/**/*.css"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/*.ts"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/*.module.scss"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/*.tsx"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/*.css"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/*.css.map"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/*.tsx"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/*.scss"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/*.css"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/*.css.map"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/*.tsx"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/*.module.scss"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/*.css"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/*.css.map"
            dest: /shell-mf/src
            strip: "src/"


          - src: "src/**/**/**/**/*.tsx"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/*.module.scss"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/*.css"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/*.css.map"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.tsx"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.module.scss"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.css"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.css.map"
            dest: /shell-mf/src
            strip: "src/"


          - src: "src/**/**/**/**/**/**/*.tsx"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.module.scss"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.css"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.css.map"
            dest: /shell-mf/src
            strip: "src/"


          - src: "src/**/**/**/**/**/**/**/*.tsx"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/*.module.scss"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/*.css"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/*.css.map"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/**/*.tsx"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/**/*.module.scss"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/**/*.css"
            dest: /shell-mf/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/**/*.css.map"
            dest: /shell-mf/src
            strip: "src/"
      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - k8s/service.yaml
    - k8s/deployment.yaml

deploy:
  kubectl: {}
